In [ ]:
# En esta celda se puede probar la funcion de analisis de una imagen

from lib.image import image_data
from lib.analysis import dyssynchonia_analysis
import cv2

# Path completo donde esta la imagen (incluyendo nombre y extencion)
path = 'photos_examples/c1d000.tif'

# Ancho de la feta a analisar (es un parametro opcional)
ancho_corte = 5

# Distancia minima en pixeles entre picos
min_dist_between_maxs = 20

image = cv2.imread(path)
# Select ROI
fromCenter = False
showCrosshair = False
seleted_parameters = cv2.selectROI(image, fromCenter, showCrosshair)

# Crop image
x_start = int(seleted_parameters[1])
x_end = x_start + int(seleted_parameters[3])
y_start = int(seleted_parameters[0])
y_end = y_start + int(seleted_parameters[2])

cv2.destroyAllWindows()

image = image_data.get_image_data(image)
image = image_data.crop_vertical(image, x_start, x_end)
image = image_data.crop_horizontal(image, y_start, y_end)

results = dyssynchonia_analysis.analyze_image(image, min_dist_between_maxs, ancho_corte)

# PRUEBA ANALISIS 

In [1]:
# En esta celda se puede probar la funcion de analisis todas las imagenes .tif en un directorio
import os
from lib.image import image_data
from lib.analysis import dyssynchonia_analysis
import cv2

# Ancho de la feta a analisar (es un parametro opcional)
ancho_corte = 5

# Distancia minima en pixeles entre picos
min_dist_between_maxs = 20


# Path donde estan las imagenes
path = "C:/Users/Leand/OneDrive/Documentos/Lean/Analizador_imagenes_calcio/seleccion/050320sel/050320c1"

images_paths = [ f'{path}/{file}' for file in os.listdir(path) if file.endswith(".tif") ]
images = [ cv2.imread(image_path) for image_path in images_paths ]

In [2]:
fromCenter = False
showCrosshair = False

#Tomamos la primer imagen para seleccionar el recorte elegido el resto de las imagenes se van a recortar igual
seleted_parameters = cv2.selectROI(images[0], fromCenter, showCrosshair)

# Crop image
x_start = int(seleted_parameters[1])
x_end = x_start + int(seleted_parameters[3])
y_start = int(seleted_parameters[0])
y_end = y_start + int(seleted_parameters[2])

cv2.destroyAllWindows()

In [3]:
images = [ image_data.get_image_data(image) for image in images ]
images = [ image_data.crop_vertical(image, x_start, x_end) for image in images ]
images = [ image_data.crop_horizontal(image, y_start, y_end) for image in images ]
images

[array([[8, 8, 8, ..., 8, 8, 8],
        [8, 8, 8, ..., 8, 8, 8],
        [8, 8, 8, ..., 8, 8, 8],
        ...,
        [8, 8, 8, ..., 8, 8, 8],
        [8, 7, 7, ..., 8, 8, 8],
        [8, 7, 7, ..., 8, 8, 8]], dtype=uint8),
 array([[12, 12, 13, ..., 11, 11, 12],
        [12, 12, 12, ..., 11, 11, 11],
        [12, 12, 12, ..., 11, 11, 11],
        ...,
        [13, 13, 13, ..., 18, 18, 18],
        [13, 13, 13, ..., 18, 18, 18],
        [13, 13, 13, ..., 18, 18, 18]], dtype=uint8),
 array([[16, 16, 16, ..., 16, 16, 16],
        [16, 16, 16, ..., 16, 16, 16],
        [16, 16, 16, ..., 16, 16, 16],
        ...,
        [13, 13, 13, ..., 13, 13, 13],
        [13, 13, 13, ..., 13, 13, 13],
        [13, 13, 13, ..., 13, 13, 13]], dtype=uint8),
 array([[ 9,  9,  9, ..., 21, 21, 21],
        [ 9,  9,  9, ..., 20, 20, 21],
        [ 9,  9,  9, ..., 20, 20, 20],
        ...,
        [ 9,  9, 10, ..., 15, 15, 15],
        [ 9,  9,  9, ..., 14, 15, 15],
        [ 9,  9,  9, ..., 14, 15, 15]], dt

In [4]:
[dyssynchonia_analysis.analyze_image(image, min_dist_between_maxs, ancho_corte) for image in images]

[{'image': {'intensities': array([ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
           7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
           7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
           7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
           7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
           7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
           7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,
           8,  9,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 20, 21, 22,
          22, 22, 22, 23, 23, 22, 22, 22, 22, 22, 22, 22, 21, 21, 21, 21, 21,
          21, 20, 20, 20, 20, 20, 19, 19, 19, 19, 19, 19, 18, 18, 18, 18, 18,
          18, 17, 17, 17, 17, 17, 16, 16, 16, 16, 16, 16, 16, 16, 15, 15, 15,
          15, 15, 15, 14, 14, 14, 14, 14, 14, 14, 14, 13, 13, 13, 13, 13, 13,
          13, 13, 12, 12, 12, 12, 12, 12

# Analisis de datos
Notas: 
- Image corresponde al análisis de toda la célula y slices corresponde a fetas de esa imagen
- intensidades es el valor que resulta de comprimir (sumando) la matriz con las coordenadas de x,y,z de los pixeles 
- max_peaks_pos es la index de en la lista de intensidades 
- max_peaks_intensities el valor de intensidad que se corresponde con el pico en la posicion analoga de max_peaks_pos

In [1]:
#Imports
import json
import numpy as np
import pandas as pd

In [6]:
#encodes a dictionary into a jason
class NumpyEncoder(json.JSONEncoder):
    """ Special json encoder for numpy types """
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        return json.JSONEncoder.default(self, obj)


def jasonGenerator(path,results):
    """ Generates a .jason file in the path given folder from the a dictionary """
    with open(path + '/analysis_result.jason',"w") as miarch:
        miarch.write(json.dumps(reslust, cls=NumpyEncoder))

In [2]:
def jasonReader(path):
    """ Reads the .jason generated with jasonGenartor the given path"""
    with open( path + '/analysis_result.json','r') as miarch:
        loaded_dict = json.loads(miarch.read())
    return loaded_dict

In [58]:
def slicesParser_max_peaksI(path):
    #read the analysis result 
    dictres = jasonReader(path)
    
    #extract all the slices data
    allSlices = dictres['slices']
    
    #seting columns names
    column_names = ['transient' + str(x+1) for x in range(0,len(allSlices[0]['max_peaks_intensities']))]
    
    #define a dataframe
    df_sum = pd.DataFrame(columns=column_names)

    for i in range(0,len(allSlices)):
        df_sum.loc[i+1] = allSlices[i]['max_peaks_intensities']

    return df_sum

In [64]:
def slicesParser_halfpeakstime(path):
    #read the analysis result 
    dictres = jasonReader(path)
    #extract all the slices data
    allSlices = dictres['slices']
    #seting columns names
    column_names = ['transient' + str(x+1) for x in range(0,len(allSlices[0]['times_to_half_peaks']))]
    #define a dataframe
    df_sum = pd.DataFrame(columns=column_names)
    #populating the dataframe
    for i in range(0,len(allSlices)):
        df_sum.loc[i+1] = allSlices[i]['times_to_half_peaks']

    return df_sum

In [66]:
path_arch = '/home/ana/Proyectos_Lean/CardiAP/DesktopApp'

slicesParser_max_peaksI(path_arch).head(2)

transient1 transient2 transient3 transient4 transient5 transient6
1         54         53         51         52         55         53
2         54         53         52         51         54         51

In [67]:
slicesParser_halfpeakstime(path_arch).head(2)

transient1 transient2 transient3 transient4 transient5
1         74        155        231        307        385
2         73        153        231        309        387

In [63]:
dictres = jasonReader(path)

allSlices = dictres['slices']

allSlices[0].keys()

dict_keys(['intensities', 'max_peaks_positions', 'max_peaks_intensities', 'min_peaks_positions', 'min_peaks_intensities', 'amplitudes', 'times_to_peaks', 'times_to_half_peaks', 'tau_s'])