In [ ]:
# En esta celda se puede probar la funcion de analisis de una imagen

from lib.image import image_data
from lib.analysis import dyssynchrony_analysis
import cv2

# Path completo donde esta la imagen (incluyendo nombre y extencion)
path = 'C:/Users/Leand/OneDrive/Documentos/Lean/Analizador_imagenes_calcio/seleccion/050320sel/050320c1/'
photo_name = '1b000.tif'
# Ancho de la feta a analisar (es un parametro opcional)
ancho_corte = 5

# Distancia minima en pixeles entre picos
min_dist_between_maxs = 20

# Calibracion del tiempo de cada pixel
calibration = 3.1

image = cv2.imread(path + photo_name)
# Select ROI
fromCenter = False
showCrosshair = False
seleted_parameters = cv2.selectROI(image, fromCenter, showCrosshair)

# Crop image
x_start = int(seleted_parameters[1])
x_end = x_start + int(seleted_parameters[3])
y_start = int(seleted_parameters[0])
y_end = y_start + int(seleted_parameters[2])

cv2.destroyAllWindows()

image = image_data.get_image_data(image)
image = image_data.crop_vertical(image, x_start, x_end)
image = image_data.crop_horizontal(image, y_start, y_end)

results = dyssynchrony_analysis.analyze_image(image, min_dist_between_maxs, calibration, slice_width=ancho_corte)

# PRUEBA ANALISIS 

In [1]:
# En esta celda se puede probar la funcion de analisis todas las imagenes .tif en un directorio
import os
from lib.image import image_data
from lib.analysis import dyssynchrony_analysis
import cv2

# Ancho de la feta a analisar (es un parametro opcional)
ancho_corte = 5

# Distancia minima en pixeles entre picos
min_dist_between_maxs = 20


# Path donde estan las imagenes
path = "C:/Users/Leand/OneDrive/Documentos/Lean/Analizador_imagenes_calcio/seleccion/050320sel/050320c2"

images_paths = [ f'{path}/{file}' for file in os.listdir(path) if file.endswith(".tif") ]
images = [ cv2.imread(image_path) for image_path in images_paths ]

In [2]:
fromCenter = False
showCrosshair = False

#Tomamos la primer imagen para seleccionar el recorte elegido el resto de las imagenes se van a recortar igual
seleted_parameters = cv2.selectROI(images[0], fromCenter, showCrosshair)

# Crop image
x_start = int(seleted_parameters[1])
x_end = x_start + int(seleted_parameters[3])
y_start = int(seleted_parameters[0])
y_end = y_start + int(seleted_parameters[2])

cv2.destroyAllWindows()

In [3]:
images = [ image_data.get_image_data(image) for image in images ]
images = [ image_data.crop_vertical(image, x_start, x_end) for image in images ]
images = [ image_data.crop_horizontal(image, y_start, y_end) for image in images ]
images

[array([[14, 14, 14, ..., 15, 15, 15],
        [14, 14, 14, ..., 15, 15, 15],
        [14, 14, 14, ..., 15, 16, 15],
        ...,
        [13, 14, 14, ..., 15, 15, 15],
        [13, 14, 14, ..., 15, 15, 15],
        [13, 14, 14, ..., 15, 15, 15]], dtype=uint8),
 array([[14, 14, 15, ..., 16, 16, 16],
        [14, 14, 14, ..., 16, 16, 16],
        [14, 14, 14, ..., 16, 16, 16],
        ...,
        [14, 14, 14, ..., 15, 15, 15],
        [14, 14, 14, ..., 15, 15, 15],
        [14, 14, 14, ..., 15, 15, 15]], dtype=uint8),
 array([[22, 22, 22, ..., 25, 25, 25],
        [22, 22, 22, ..., 25, 25, 25],
        [22, 22, 22, ..., 24, 25, 25],
        ...,
        [19, 20, 19, ..., 23, 23, 23],
        [19, 20, 20, ..., 23, 23, 23],
        [20, 19, 19, ..., 23, 23, 23]], dtype=uint8),
 array([[20, 20, 20, ..., 23, 23, 23],
        [20, 20, 20, ..., 23, 23, 23],
        [19, 20, 20, ..., 23, 23, 23],
        ...,
        [20, 20, 20, ..., 22, 21, 22],
        [20, 20, 20, ..., 21, 21, 21],
      

In [5]:
results = [dyssynchrony_analysis.analyze_image(image, min_dist_between_maxs, ancho_corte) for image in images]

# Analisis de datos
Notas: 
- Image corresponde al análisis de toda la célula y slices corresponde a fetas de esa imagen
- intensidades es el valor que resulta de comprimir (sumando) la matriz con las coordenadas de x,y,z de los pixeles 
- max_peaks_pos es la index de en la lista de intensidades 
- max_peaks_intensities el valor de intensidad que se corresponde con el pico en la posicion analoga de max_peaks_pos

In [6]:
#Imports
import json
import numpy as np
import pandas as pd

In [7]:
#encodes a dictionary into a jason
class NumpyEncoder(json.JSONEncoder):
    """ Special json encoder for numpy types """
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        return json.JSONEncoder.default(self, obj)


def jasonGenerator(path,results):
    """ Generates a .jason file in the path given folder from the a dictionary """
    with open(path + '/analysis_result.json',"w") as miarch:
        miarch.write(json.dumps(results, cls=NumpyEncoder))

In [8]:
def jasonReader(path):
    """ Reads the .jason generated with jasonGenartor the given path"""
    with open( path + '/analysis_result.json','r') as miarch:
        loaded_dict = json.loads(miarch.read())
    return loaded_dict

In [9]:
def slicesParser_max_peaksI(path):
    #read the analysis result 
    dictres = jasonReader(path)

    #extract all the slices data
    allSlices = dictres['slices']
    
    try:
        #seting columns names
        column_names = ['transient' + str(x) for x in range(1,len(allSlices[0]['max_peaks_intensities']))]

        #define a dataframe
        df_sum = pd.DataFrame(columns=column_names)

        for i in range(1,len(allSlices)):
            df_sum.loc[i+1] = allSlices[i]['max_peaks_intensities'][1:]

        return df_sum
    
    except:
        print('no possible callculation')

In [10]:
def slicesParser_halfpeakstime(path):
    #read the analysis result 
    dictres = jasonReader(path)
    #extract all the slices data
    allSlices = dictres['slices']
    try:
        #seting columns names
        column_names = ['transient' + str(x+1) for x in range(0,len(allSlices[0]['times_to_half_peaks']))]
        #define a dataframe
        df_sum = pd.DataFrame(columns=column_names)
        #populating the dataframe
        for i in range(0,len(allSlices)):
            df_sum.loc[i+1] = allSlices[i]['times_to_half_peaks']

        return df_sum

    except:
        print('no possible callculation')

In [11]:
def slicesParser_amplitudes(path):
    #read the analysis result 
    dictres = jasonReader(path)
    #extract all the slices data
    allSlices = dictres['slices']
    try:
        #seting columns names
        column_names = ['transient' + str(x+1) for x in range(0,len(allSlices[0]['amplitudes']))]
        #define a dataframe
        df_sum = pd.DataFrame(columns=column_names)
        #populating the dataframe
        for i in range(0,len(allSlices)):
            df_sum.loc[i+1] = allSlices[i]['amplitudes']

        return df_sum
    
    except:
        print('no possible callculation')

In [12]:
def slicesParser_min_peaksI(path):
    #read the analysis result 
    dictres = jasonReader(path)
    #extract all the slices data
    allSlices = dictres['slices']
    try:
        #seting columns names
        column_names = ['transient' + str(x+1) for x in range(0,len(allSlices[0]['min_peaks_intensities']))]
        #define a dataframe
        df_sum = pd.DataFrame(columns=column_names)
        #populating the dataframe
        for i in range(0,len(allSlices)):
            df_sum.loc[i+1] = allSlices[i]['min_peaks_intensities']

        return df_sum
    
    except:
        print('no possible callculation')

In [13]:
def slicesParser_peaktime(path):
    #read the analysis result 
    dictres = jasonReader(path)
    #extract all the slices data
    allSlices = dictres['slices']

    try:
        #seting columns names
        column_names = ['transient' + str(x+1) for x in range(0,len(allSlices[0]['times_to_peaks']))]
        #define a dataframe
        df_sum = pd.DataFrame(columns=column_names)
        #populating the dataframe
        for i in range(0,len(allSlices)):
            df_sum.loc[i+1] = allSlices[i]['times_to_peaks']

        return df_sum
    
    except:
        print('no possible callculation')

In [14]:
def slicesParser_tau(path):
    #read the analysis result 
    dictres = jasonReader(path)
    #extract all the slices data
    allSlices = dictres['slices']
    #seting columns names
    try:
        column_names = ['transient' + str(x+1) for x in range(0,len(allSlices[0]['tau_s']))]
        #define a dataframe
        df_sum = pd.DataFrame(columns=column_names)
        #populating the dataframe
        for i in range(0,len(allSlices)):
            df_sum.loc[i+1] = allSlices[i]['tau_s']
        
        return df_sum
    
    except:
        print('no possible callculation')

In [15]:
def BasicStasts(df):
    if df.empty == False:
        return df.astype('int').describe()

In [16]:
def discordIndex(df):
    return df.iloc[2].mean()

In [17]:
def amplitudes_ratio(df):
    df_alt = pd.DataFrame()
    for i in range(0,len(list(df))-1):
        name = 'ratio' + str(i+1) +'-' + str(i)
        df_alt[name] = df[list(df)[i+1]]/df[list(df)[i]]
    return df_alt

In [18]:
jasonGenerator(path,results)

In [20]:
path_arch = path

BasicStasts(slicesParser_max_peaksI(path_arch))

TypeError: list indices must be integers or slices, not str

In [21]:
amplitudes_ratio(slicesParser_amplitudes(path_arch))

TypeError: list indices must be integers or slices, not str

In [ ]:
slicesParser_min_peaksI(path_arch).head(2)

In [ ]:
slicesParser_tau(path_arch)

In [ ]:
dicto1 = jasonReader('/home/ana/CardiAp/DesktopApp')

In [ ]:
#dicto1['slices'][0]
dicto1['image']